[package]
name = "rit"
version = "0.1.0"
edition = "2024"

[dependencies]
filetime = "0.2.25"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
sha2 = "0.10.8"

[dev-dependencies]
rand = "0.9.0"
tempdir = "0.3.7"
